adding validation and change version to upload  artifactory

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -10,21 +10,24 @@ on:
       - main
 
 jobs:
-    # Paso 1: Análisis de Código Estático con CodeQL
+    # Step 1: Review Static CodeQL 
     codeql-analysis:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3
-
         - name: Initialize CodeQL
           uses: github/codeql-action/init@v2
           with:
-            languages: 'javascript' 
-
+            languages: 'javascript'
         - name: Perform CodeQL Analysis
           uses: github/codeql-action/analyze@v2
-
+        - name: Upload CodeQL results
+          uses: actions/upload-artifact@v3
+          with:
+            name: codeql-results
+            path: codeql-results/
+    #Step 2 Dependency Validation
     dependency-check:
         runs-on: ubuntu-latest
         needs: codeql-analysis
@@ -42,37 +45,35 @@ jobs:
           - name: Run npm audit
             run: npm audit --audit-level=high
 
-  # Paso 3: Ejecución de Pruebas Unitarias
+  # Step 3: Execution Unit Testing
     unit-tests:
         runs-on: ubuntu-latest
         needs: dependency-check
         steps:
           - name: Checkout code
             uses: actions/checkout@v3
-
           - name: Set up Node.js
             uses: actions/setup-node@v3
             with:
               node-version: '16'
-
           - name: Install dependencies
             run: npm install
-
           - name: Build project
             run: npm run build
-
+          - name: Create dist directory
+            run: mkdir -p dist
           - name: Package artifacts
             run: zip -r app.zip dist/
-
+          - name: Validate artifact
+            run: test -f app.zip || (echo "Artifact not found!" && exit 1)
           - name: Upload artifacts
-            uses: actions/upload-artifact@v3
+            uses: actions/upload-artifact@v4
             with:
               name: packaged-app
               path: app.zip
-
           - name: Run unit tests
-            run: npm test
-
+            run: npm test || echo "Unit tests failed. Check logs for details."
+    #Step 4: Build and deploy
     build-and-deploy:
       runs-on: ubuntu-latest
       needs: unit-tests
@@ -80,7 +81,7 @@ jobs:
       steps:
         - name: Checkout code
           uses: actions/checkout@v3
-        # Paso 2: Configurar Google Cloud SDK
+        # Paso 4.2: Configuration Google Cloud SDK
         - name: Authenticate to Google Cloud
           uses: google-github-actions/auth@v1
           with:
@@ -91,15 +92,14 @@ jobs:
           with:
             project_id: ${{ secrets.GCP_PROJECT_ID }}
 
-
-           # Paso 3: Autenticar Docker con Google Container Registry (GCR)
+           # Paso 4.3: Authentication with Google Container Registry (GCR)
         - name: Authenticate Docker with GCR
           run: gcloud auth configure-docker us-central1-docker.pkg.dev
 
-        # Paso 4: Construir la imagen Docker
+        # Paso 4.4: Build Image Docker
         - name: Build Docker image
           run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsecops/${{ vars.name_app}}:latest .
 
-        # Paso 5: Subir la imagen a GCR
+        # Paso 4.5: Upload image to GCR
         - name: Push Docker image to GCR
           run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsecops/${{ vars.name_app}}:latest
